# Generated by Django 3.2.4 on 2021-06-24 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(max_length=200)),
                ('data', models.DateTimeField(verbose_name='date_activity')),
                ('activity', models.CharField(max_length=200)),
                ('emotions', models.CharField(max_length=200)),
            ],
        ),
    ]
